# Generated by Django 5.2.7 on 2025-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small square icon used in the top belt', upload_to='category-icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='nav_label',
            field=models.CharField(blank=True, help_text='Optional short label to display instead of name', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='nav_order',
            field=models.PositiveIntegerField(default=0, help_text='Smaller comes first'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_nav',
            field=models.BooleanField(default=False, help_text='Show in the top category belt'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_nav', 'nav_order'], name='catalog_cat_show_in_4d29e4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent__5307be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_f6911e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary', 'sort'], name='catalog_pro_product_30fa67_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='catalog_pro_product_460665_idx'),
        ),
    ]
