# Generated by Django 5.2.7 on 2025-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expected_restock_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='backorder_policy',
            field=models.CharField(choices=[('block', 'Block'), ('allow', 'Allow'), ('notify', 'Notify')], default='block', max_length=30),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(max_length=180),
        ),
    ]
