# Generated by Django 5.2.7 on 2025-10-11 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='returns/')),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.returnrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['return_request', 'created_at'], name='orders_retu_return__7ef0b8_idx')],
            },
        ),
    ]
