# Generated by Django 5.2.7 on 2025-10-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderevent_paymentidempotency_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
