# Generated by Django 5.2.7 on 2025-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='orders_addr_postal__eb4cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'state'], name='orders_addr_city_9810ad_idx'),
        ),
    ]
