# Generated by Django 5.2.6 on 2025-10-08 09:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat'), ('table', 'Table')], default='flat', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_over', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='shipping_sh_is_acti_c9ab92_idx'), models.Index(fields=['rate_type'], name='shipping_sh_rate_ty_ce0049_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=60)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked', 'Picked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], db_index=True, default='created', max_length=20)),
                ('events', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingmethod')),
            ],
        ),
    ]
