# Generated by Django 5.2.7 on 2025-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_address_orders_addr_postal__eb4cb8_idx_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_no',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'created_at'], name='shipping_sh_order_i_4ad347_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_58d901_idx'),
        ),
    ]
