# Generated by Django 5.2.7 on 2025-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('view_all', models.CharField(blank=True, help_text='Frontend URL to a filtered listing (e.g. /search?deals=1).', max_length=300)),
                ('source_path', models.CharField(blank=True, help_text='(Optional) API path to fetch items server-side later, e.g. /catalog/products/', max_length=300)),
                ('params_json', models.JSONField(blank=True, default=dict, help_text='(Optional) Query params for server-side fetching later.')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Rail',
                'verbose_name_plural': 'Home Rails',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
