# Generated by Django 5.2.7 on 2025-10-20 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homerail'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='homerail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homerail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='alt',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='homerail',
            name='view_all',
            field=models.CharField(blank=True, help_text='Frontend URL to a filtered listing (e.g. /search?price_max=999).', max_length=300),
        ),
        migrations.AddIndex(
            model_name='homebanner',
            index=models.Index(fields=['is_active', 'sort'], name='cms_homeban_is_acti_a1cdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='homerail',
            index=models.Index(fields=['is_active', 'sort'], name='cms_homerai_is_acti_296707_idx'),
        ),
    ]
