# Generated by Django 5.2.7 on 2025-10-17 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_returnrequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], db_index=True, max_length=32, unique=True)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('secret_key', models.CharField(blank=True, max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('live_mode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configurations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], db_index=True, default='razorpay', max_length=30)),
                ('provider_order_id', models.CharField(db_index=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refunded', 'Partial Refunded')], db_index=True, default='created', max_length=30)),
                ('amount_paise', models.PositiveIntegerField(help_text='Total charge amount in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('refund_id', models.CharField(blank=True, max_length=120)),
                ('refund_amount_paise', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], db_index=True, default='razorpay', max_length=30)),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'provider'], name='payments_pa_order_i_d99049_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_order_id'], name='payments_pa_provide_c37514_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_payment_id'], name='payments_pa_provide_adf74c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_order_id'), name='uniq_provider_order_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id__isnull', False)), fields=('provider', 'provider_payment_id'), name='uniq_provider_payment_per_provider'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['provider', 'event_type'], name='payments_pa_provide_8f6ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['created_at'], name='payments_pa_created_4b9611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentevent',
            unique_together={('provider', 'event_id')},
        ),
    ]
