# Generated by Django 5.2.7 on 2025-10-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'indexes': [models.Index(fields=['wishlist', 'created_at'], name='wishlist_wi_wishlis_81d127_idx'), models.Index(fields=['wishlist', 'variant'], name='wishlist_wi_wishlis_e420b2_idx'), models.Index(fields=['wishlist', 'product'], name='wishlist_wi_wishlis_781718_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False), _connector='OR'), name='wishlistitem_has_target'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('wishlist', 'variant'), name='uq_wishlist_variant'), models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', True)), fields=('wishlist', 'product'), name='uq_wishlist_product_when_no_variant')],
            },
        ),
    ]
