# Generated by Django 5.2.7 on 2025-10-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
